base_url = "https://sirodoht.github.io/zola-henry/"

title = "Dr. Henry Jekyll"
description = "A timeless blog theme"
compile_sass = false
highlight_code = true
generate_rss = true

[extra]
henry_links = [
    {url = "about", name = "About"},
]
henry_github = "https://github.com/sirodoht/zola-henry"
henry_twitter = "https://twitter.com/jekyllrb"
